import { writable } from "svelte/store";
import type { AppConfig } from "$lib/types/app";

export const appConfig = writable<AppConfig>({
  language: "en",
  theme: "default",
  toolbarButtonSize: "large",
  imageNameDisplayMode: "fade",
  edgeIndicatorsVisible: false,
  rememberWindowSize: false,
  linuxDesktopInstallChoice: "not_asked",
  shortcuts: {
    openFile: { keys: [], label: "" },
    saveImageAs: { keys: [], label: "" },
    previousImage: { keys: [], label: "" },
    nextImage: { keys: [], label: "" },
    zoomIn: { keys: [], label: "" },
    zoomOut: { keys: [], label: "" },
    toggleExif: { keys: [], label: "" },
    toggleFullscreen: { keys: [], label: "" },
    toggleOptions: { keys: [], label: "" },
    zoomModifierUp: { keys: [], label: "" },
    zoomModifierDown: { keys: [], label: "" },
    rotateClockwise: { keys: [], label: "" },
    rotateCounterclockwise: { keys: [], label: "" },
    convertToAsciiArt: { keys: [], label: "" },
  },
  customShortcuts: {
    openFile: { keys: [], label: "" },
    saveImageAs: { keys: [], label: "" },
    previousImage: { keys: [], label: "" },
    nextImage: { keys: [], label: "" },
    zoomIn: { keys: [], label: "" },
    zoomOut: { keys: [], label: "" },
    toggleExif: { keys: [], label: "" },
    toggleFullscreen: { keys: [], label: "" },
    toggleOptions: { keys: [], label: "" },
    zoomModifierUp: { keys: [], label: "" },
    zoomModifierDown: { keys: [], label: "" },
    rotateClockwise: { keys: [], label: "" },
    rotateCounterclockwise: { keys: [], label: "" },
    convertToAsciiArt: { keys: [], label: "" },
  },
});
